spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        ddl-auto: false
    hibernate:
      id:
        new:
          new_generator_mappings: true
    show-sql: true
    databases: mysql
    generate-ddl: false
    driver-class-name: com.mysql.cj.jdbc.Driver